### ISSUE TITLE
This belongs in core :)

### ISSUE THREAD

**Issue by raiph** [tadzik/Typed-Subroutines#4]
Hi tadzik,

I just saw this module and wondered what it was so took a peek.

It's great stuff that belongs in core! And it is! :)

`subset Foo of Sub where :($, Str)`

etc.

Maybe it makes sense to honorably retire this pioneering module? :)

**Comment by tadzik** [comment]
Haha, I had no idea! I only hope that this feature is indeed newer than this module :P

In that case, I'm going to issue a deprecation warning in case someone actually uses this module in the wild and honorably retire it from the ecosystem :) Thanks a lot for pointing it out!
